import type { Language, Module } from '../../../../types/answers.js';

export async function pgPrisma(language: Language, ext: '.js' | '.ts', module: Module) {
  const client = `
${module === 'commonjs' ? 'const { PrismaPg } =require("@prisma/adapter-pg");' : 'import { PrismaPg } from "@prisma/adapter-pg";'}
${module === 'commonjs' ? 'const { PrismaClient } = require("@prisma/client");' : 'import { PrismaClient } from "@prisma/client"'};

const connectionString = process.env.DATABASE_URL;

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

${module === 'commonjs' ? 'module.exports =  { prisma };' : 'export { prisma };'}
`;

  const schema = `
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "${language === 'javascript' ? 'prisma-client-js' : 'prisma-client'}"
  ${module === 'commonjs' ? 'moduleFormat = "cjs"' : ''}
}

datasource db {
  provider = "postgresql"
}
`;

  const config = `
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
${module === 'commonjs' ? 'require("dotenv").config();' : 'import "dotenv/config";'}
${module === 'commonjs' ? 'const { defineConfig } =require("prisma/config");' : 'import { defineConfig } from "prisma/config";'}

${module === 'commonjs' ? 'module.exports =' : 'export default'} defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
`;

  const files = [
    { name: 'prisma/schema.prisma', content: schema },
    { name: `src/config/db${ext}`, content: client },
    { name: `prisma.config${ext}`, content: config },
  ];

  return files;
}

export async function mysqlPrisma(language: Language, ext: '.js' | '.ts', module: Module) {
  const client = `
${module === 'commonjs' ? 'const { PrismaMariaDb } =require("@prisma/adapter-mariadb");' : 'import { PrismaPg } from "@prisma/adapter-mariadb";'}
${module === 'commonjs' ? 'const { PrismaClient } = require("@prisma/client");' : 'import { PrismaClient } from "@prisma/client"'};

const adapter = new PrismaMariaDb({
  host: process.env.DATABASE_HOST,
  user: process.env.DATABASE_USER,
  password: process.env.DATABASE_PASSWORD,
  database: process.env.DATABASE_NAME,
  connectionLimit: 5,
});
const prisma = new PrismaClient({ adapter });

${module === 'commonjs' ? 'module.exports =  { prisma };' : 'export { prisma };'}
`;

  const schema = `
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "${language === 'javascript' ? 'prisma-client-js' : 'prisma-client'}"
  ${module === 'commonjs' ? 'moduleFormat = "cjs"' : ''}
}

datasource db {
  provider = "mysql"
}
`;

  const config = `
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
${module === 'commonjs' ? 'require("dotenv").config();' : 'import "dotenv/config";'}
${module === 'commonjs' ? 'const { defineConfig } =require("prisma/config");' : 'import { defineConfig } from "prisma/config";'}

${module === 'commonjs' ? 'module.exports =' : 'export default'} defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
`;

  const files = [
    { name: 'prisma/schema.prisma', content: schema },
    { name: `src/config/db${ext}`, content: client },
    { name: `prisma.config${ext}`, content: config },
  ];

  return files;
}
