import { select } from "@inquirer/prompts";

export async function ormPrompt(
  database: string
  ) {
    switch (database) {
        case "mongodb":
              return select({
                      message: "Select ODM:",
                              choices: [
                                        {
                                                    name: "Mongoose",
                                                                value: "mongoose",
                                                                          },
                                                                                    {
                                                                                                name: "None",
                                                                                                            value: "none",
                                                                                                                      },
                                                                                                                              ],
                                                                                                                                    });

                                                                                                                                        case "postgresql":
                                                                                                                                              return select({
                                                                                                                                                      message: "Select ORM:",
                                                                                                                                                              choices: [
                                                                                                                                                                        {
                                                                                                                                                                                    name: "Prisma",
                                                                                                                                                                                                value: "prisma",
                                                                                                                                                                                                          },
                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                name: "Drizzle",
                                                                                                                                                                                                                                            value: "drizzle",
                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                            name: "Sequelize",
                                                                                                                                                                                                                                                                                        value: "sequelize",
                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                        name: "None",
                                                                                                                                                                                                                                                                                                                                    value: "none",
                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                case "mysql":
                                                                                                                                                                                                                                                                                                                                                                      return select({
                                                                                                                                                                                                                                                                                                                                                                              message: "Select ORM:",
                                                                                                                                                                                                                                                                                                                                                                                      choices: [
                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                            name: "Prisma",
                                                                                                                                                                                                                                                                                                                                                                                                                        value: "prisma",
                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        name: "Drizzle",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value: "drizzle",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: "Sequelize",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value: "sequelize",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name: "None",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }